version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017
  api:
    build: ./server
    volumes:
      - ./server/api:/srv/app/api
    ports:
      - 3004:3004
    links:
      - mongo
